=== woodcutapp/woodcutapp.github.io/public/lang/schema/app-menu.json
{
  "$ref": "#/definitions/AppMenuJsonSchema",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "AppMenuJsonSchema": {
      "additionalProperties": false,
      "properties": {
        "back": {
          "type": "string"
        },
        "edit": {
          "type": "string"
        },
        "edit.copy": {
          "type": "string"
        },
        "edit.delete": {
          "type": "string"
        },
        "edit.duplicate": {
          "type": "string"
        },
        "edit.history.redo": {
          "type": "string"
        },
        "edit.history.undo": {
          "type": "string"
        },
        "edit.new.board": {
          "type": "string"
        },
        "edit.new.component": {
          "type": "string"
        },
        "edit.new.cut": {
          "type": "string"
        },
        "edit.paste": {
          "type": "string"
        },
        "edit.transform.disable": {
          "type": "string"
        },
        "edit.transform.enable": {
          "type": "string"
        },
        "edit.visibility.all.hide": {
          "type": "string"
        },
        "edit.visibility.all.show": {
          "type": "string"
        },
        "edit.visibility.hide": {
          "type": "string"
        },
        "edit.visibility.show": {
          "type": "string"
        },
        "file": {
          "type": "string"
        },
        "file.export": {
          "type": "string"
        },
        "file.export.gtlf": {
          "type": "string"
        },
        "file.export.obj": {
          "type": "string"
        },
        "file.export.ply": {
          "type": "string"
        },
        "file.export.png": {
          "type": "string"
        },
        "file.export.stl": {
          "type": "string"
        },
        "file.export.xslx": {
          "type": "string"
        },
        "file.new": {
          "type": "string"
        },
        "file.open": {
          "type": "string"
        },
        "file.save": {
          "type": "string"
        },
        "mode.dark": {
          "type": "string"
        },
        "mode.light": {
          "type": "string"
        },
        "selection": {
          "type": "string"
        },
        "selection.find": {
          "type": "string"
        },
        "selection.next": {
          "type": "string"
        },
        "selection.previous": {
          "type": "string"
        },
        "selection.select.all": {
          "type": "string"
        },
        "selection.select.none": {
          "type": "string"
        },
        "view": {
          "type": "string"
        },
        "view.active": {
          "type": "string"
        },
        "view.active.dimension": {
          "type": "string"
        },
        "view.active.disable": {
          "type": "string"
        },
        "view.active.enable": {
          "type": "string"
        },
        "view.active.info": {
          "type": "string"
        },
        "view.active.position": {
          "type": "string"
        },
        "view.active.rotation": {
          "type": "string"
        },
        "view.camera.orthographic": {
          "type": "string"
        },
        "view.camera.perspective": {
          "type": "string"
        },
        "view.drawer.disable": {
          "type": "string"
        },
        "view.drawer.enable": {
          "type": "string"
        },
        "view.focused.disable": {
          "type": "string"
        },
        "view.focused.disabled": {
          "type": "string"
        },
        "view.focused.enable": {
          "type": "string"
        },
        "view.focused.enabled": {
          "type": "string"
        },
        "view.grid.axis.none": {
          "type": "string"
        },
        "view.grid.axis.primary.imperial": {
          "type": "string"
        },
        "view.grid.axis.primary.metric": {
          "type": "string"
        },
        "view.grid.axis.secondary.imperial": {
          "type": "string"
        },
        "view.grid.axis.secondary.metric": {
          "type": "string"
        },
        "view.grid.axis.tertiary.imperial": {
          "type": "string"
        },
        "view.grid.axis.tertiary.metric": {
          "type": "string"
        },
        "view.grid.disable": {
          "type": "string"
        },
        "view.grid.disabled": {
          "type": "string"
        },
        "view.grid.enable": {
          "type": "string"
        },
        "view.grid.enabled": {
          "type": "string"
        },
        "view.grid.x": {
          "type": "string"
        },
        "view.grid.y": {
          "type": "string"
        },
        "view.grid.z": {
          "type": "string"
        },
        "view.ruler.disable": {
          "type": "string"
        },
        "view.ruler.disabled": {
          "type": "string"
        },
        "view.ruler.enable": {
          "type": "string"
        },
        "view.ruler.enabled": {
          "type": "string"
        },
        "view.ruler.point.a": {
          "type": "string"
        },
        "view.ruler.point.b": {
          "type": "string"
        },
        "view.ruler.point.clear": {
          "type": "string"
        },
        "view.ruler.snap.disable": {
          "type": "string"
        },
        "view.ruler.snap.enable": {
          "type": "string"
        }
      },
      "required": [
        "back",
        "edit.copy",
        "edit.delete",
        "edit.duplicate",
        "edit.history.redo",
        "edit.history.undo",
        "edit.new.board",
        "edit.new.component",
        "edit.new.cut",
        "edit.paste",
        "edit.transform.disable",
        "edit.transform.enable",
        "edit.visibility.all.hide",
        "edit.visibility.all.show",
        "edit.visibility.hide",
        "edit.visibility.show",
        "edit",
        "file.export.gtlf",
        "file.export.obj",
        "file.export.ply",
        "file.export.stl",
        "file.export.png",
        "file.export.xslx",
        "file.export",
        "file.new",
        "file.open",
        "file.save",
        "file",
        "mode.dark",
        "mode.light",
        "selection.find",
        "selection.next",
        "selection.previous",
        "selection.select.all",
        "selection.select.none",
        "selection",
        "view.active.dimension",
        "view.active.disable",
        "view.active.enable",
        "view.active.info",
        "view.active.position",
        "view.active.rotation",
        "view.active",
        "view.camera.orthographic",
        "view.camera.perspective",
        "view.drawer.disable",
        "view.drawer.enable",
        "view.focused.disable",
        "view.focused.disabled",
        "view.focused.enable",
        "view.focused.enabled",
        "view.grid.axis.none",
        "view.grid.axis.primary.imperial",
        "view.grid.axis.primary.metric",
        "view.grid.axis.secondary.imperial",
        "view.grid.axis.secondary.metric",
        "view.grid.axis.tertiary.imperial",
        "view.grid.axis.tertiary.metric",
        "view.grid.disable",
        "view.grid.disabled",
        "view.grid.enable",
        "view.grid.enabled",
        "view.grid.x",
        "view.grid.y",
        "view.grid.z",
        "view.ruler.disable",
        "view.ruler.disabled",
        "view.ruler.enable",
        "view.ruler.enabled",
        "view.ruler.point.a",
        "view.ruler.point.b",
        "view.ruler.point.clear",
        "view.ruler.snap.disable",
        "view.ruler.snap.enable",
        "view"
      ],
      "type": "object"
    }
  }
}

=== woodcutapp/woodcutapp.github.io/public/lang/zh-TW/app-menu.json
{
  "$schema": "../schema/app-menu.json",
  "back": "返回首頁",
  "edit.copy": "複製",
  "edit.delete": "刪除",
  "edit.duplicate": "快速拷貝",
  "edit.history.redo": "重做",
  "edit.history.undo": "復原",
  "edit.new.board": "新增木板",
  "edit.new.component": "新增物件組合",
  "edit.new.cut": "新增裁切",
  "edit.paste": "貼上",
  "edit.transform.disable": "停用變換模式",
  "edit.transform.enable": "啟用變換模式",
  "edit.visibility.all.hide": "隱藏全部",
  "edit.visibility.all.show": "顯示全部",
  "edit.visibility.hide": "隱藏",
  "edit.visibility.show": "顯示",
  "edit": "編輯",
  "file.export.gtlf": "GLTF",
  "file.export.obj": "OBJ",
  "file.export.ply": "PLY",
  "file.export.stl": "STL",
  "file.export.png": "PNG",
  "file.export.xslx": "XSLX",
  "file.export": "匯出",
  "file.new": "新建專案",
  "file.open": "開啟專案",
  "file.save": "儲存",
  "file": "檔案",
  "mode.dark": "切換至深色模式",
  "mode.light": "切換至淺色模式",
  "selection.find": "尋找",
  "selection.next": "下一個",
  "selection.previous": "上一個",
  "selection.select.all": "全選",
  "selection.select.none": "取消選擇",
  "selection": "選擇",
  "view.active.dimension": "尺寸面板",
  "view.active.disable": "隱藏面板",
  "view.active.enable": "顯示面板",
  "view.active.info": "資訊面板",
  "view.active.position": "位置面板",
  "view.active.rotation": "旋轉面板",
  "view.active": "作用面板",
  "view.camera.orthographic": "相機 (正交)",
  "view.camera.perspective": "相機 (透視)",
  "view.drawer.disable": "隱藏抽屜",
  "view.drawer.enable": "顯示抽屜",
  "view.focused.disable": "停用焦點模式",
  "view.focused.disabled": "焦點模式停用",
  "view.focused.enable": "啟用焦點模式",
  "view.focused.enabled": "焦點模式啟用",
  "view.grid.axis.none": "無",
  "view.grid.axis.primary.imperial": "英尺",
  "view.grid.axis.primary.metric": "公尺",
  "view.grid.axis.secondary.imperial": "英吋",
  "view.grid.axis.secondary.metric": "公分",
  "view.grid.axis.tertiary.imperial": "八分之一英吋",
  "view.grid.axis.tertiary.metric": "毫米",
  "view.grid.disable": "隱藏網格",
  "view.grid.disabled": "網格 (停用)",
  "view.grid.enable": "顯示網格",
  "view.grid.enabled": "網格 (啟用)",
  "view.grid.x": "X 網格",
  "view.grid.y": "Y 網格",
  "view.grid.z": "Z 網格",
  "view.ruler.disable": "隱藏尺規",
  "view.ruler.disabled": "尺規 (停用)",
  "view.ruler.enable": "顯示尺規",
  "view.ruler.enabled": "尺規 (啟用)",
  "view.ruler.snap.disable": "停用捕捉",
  "view.ruler.snap.enable": "啟用捕捉",
  "view.ruler.point.a": "設定點 A",
  "view.ruler.point.b": "設定點 B",
  "view.ruler.point.clear": "清除點",
  "view": "檢視"
}

=== woodcutapp/woodcutapp.github.io/public/lang/en-US/app-menu.json
{
  "$schema": "../schema/app-menu.json",
  "back": "Back to Site",
  "edit.copy": "Copy",
  "edit.delete": "Delete",
  "edit.duplicate": "Duplicate",
  "edit.history.redo": "Redo",
  "edit.history.undo": "Undo",
  "edit.new.board": "New Board",
  "edit.new.component": "New Component",
  "edit.new.cut": "New Cut",
  "edit.paste": "Paste",
  "edit.transform.disable": "Disable Transform Mode",
  "edit.transform.enable": "Enable Transform Mode",
  "edit.visibility.all.hide": "Hide All",
  "edit.visibility.all.show": "Show All",
  "edit.visibility.hide": "Hide",
  "edit.visibility.show": "Show",
  "edit": "Edit",
  "file.export.gtlf": "GL Transmission Format (GLTF)",
  "file.export.obj": "Wavefront (OBJ)",
  "file.export.ply": "Polygon (PLY)",
  "file.export.stl": "StereoLithography (STL)",
  "file.export.png": "Screenshot (PNG)",
  "file.export.xslx": "Cutlist (XLSX)",
  "file.export": "Export",
  "file.new": "New",
  "file.open": "Open",
  "file.save": "Save",
  "file": "File",
  "mode.dark": "Switch to Dark Mode",
  "mode.light": "Switch to Light Mode",
  "selection.find": "Find",
  "selection.next": "Next",
  "selection.previous": "Previous",
  "selection.select.all": "Select All",
  "selection.select.none": "Select None",
  "selection": "Selection",
  "view.active.dimension": "Dimension Panel",
  "view.active.disable": "Hide Panel",
  "view.active.enable": "Show Panel",
  "view.active.info": "Info Panel",
  "view.active.position": "Position Panel",
  "view.active.rotation": "Rotation Panel",
  "view.active": "Active Panel",
  "view.camera.orthographic": "Camera (Orthographic)",
  "view.camera.perspective": "Camera (Perspective)",
  "view.drawer.disable": "Hide Drawer",
  "view.drawer.enable": "Show Drawer",
  "view.focused.disable": "Disable Focused Mode",
  "view.focused.disabled": "Focused Mode Disabled",
  "view.focused.enable": "Enable Focused Mode",
  "view.focused.enabled": "Focused Mode Enabled",
  "view.grid.axis.none": "None",
  "view.grid.axis.primary.imperial": "Feet",
  "view.grid.axis.primary.metric": "Meters",
  "view.grid.axis.secondary.imperial": "Inches",
  "view.grid.axis.secondary.metric": "Centimeters",
  "view.grid.axis.tertiary.imperial": "Eighths",
  "view.grid.axis.tertiary.metric": "Millimeters",
  "view.grid.disable": "Hide Grid",
  "view.grid.disabled": "Grid (Disabled)",
  "view.grid.enable": "Show Grid",
  "view.grid.enabled": "Grid (Enabled)",
  "view.grid.x": "X Grid",
  "view.grid.y": "Y Grid",
  "view.grid.z": "Z Grid",
  "view.ruler.disable": "Hide Ruler",
  "view.ruler.disabled": "Ruler (Disabled)",
  "view.ruler.enable": "Show Ruler",
  "view.ruler.enabled": "Ruler (Enabled)",
  "view.ruler.snap.disable": "Disable Snap",
  "view.ruler.snap.enable": "Enable Snap",
  "view.ruler.point.a": "Set Point A",
  "view.ruler.point.b": "Set Point B",
  "view.ruler.point.clear": "Clear Points",
  "view": "View"
}
