=== woodcutapp/woodcutapp.github.io/public/lang/schema/feature.json
{
  "$ref": "#/definitions/FeatureJsonSchema",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "FeatureJsonSchema": {
      "additionalProperties": false,
      "properties": {
        "cutlist": {
          "type": "string"
        },
        "cutlist.description": {
          "type": "string"
        },
        "cuts": {
          "type": "string"
        },
        "cuts.description": {
          "type": "string"
        },
        "export": {
          "type": "string"
        },
        "export.description": {
          "type": "string"
        },
        "ruler": {
          "type": "string"
        },
        "ruler.description": {
          "type": "string"
        },
        "transform": {
          "type": "string"
        },
        "transform.description": {
          "type": "string"
        }
      },
      "required": [
        "cutlist",
        "cutlist.description",
        "cuts",
        "cuts.description",
        "export",
        "export.description",
        "ruler",
        "ruler.description",
        "transform",
        "transform.description"
      ],
      "type": "object"
    }
  }
}

=== woodcutapp/woodcutapp.github.io/public/lang/en-US/feature.json
{
  "$schema": "../schema/feature.json",
  "cutlist": "Organize and Optimize Your Project",
  "cutlist.description": "Generate a list of boards to purchase, and export exact measurements for each cut piece.",
  "cuts": "Detailed and Precise Cuts",
  "cuts.description": "Create various configurable cuts, like dovetails, dados, and tenons.",
  "export": "Export Your Project",
  "export.description": "Export your project to JSON, Excel and various 3D modeling formats.",
  "ruler": "Measure and Visualize",
  "ruler.description": "Make custom measurements for hard to visualize cuts.",
  "transform": "Transform and Manipulate",
  "transform.description": "Rotate, move, and scale your project to fit your needs."
}

=== woodcutapp/woodcutapp.github.io/public/lang/zh-TW/feature.json
{
  "$schema": "../schema/feature.json",
  "cutlist": "優化裁切清單",
  "cutlist.description": "可產生精確尺寸的裁切清單。",
  "cuts": "詳細而精確的切割",
  "cuts.description": "創建各種裁切，如半對半、槽口和榫頭。",
  "export": "匯出專案",
  "export.description": "將專案匯出為JSON、Excel和各種3D格式。",
  "ruler": "視覺化的量測",
  "ruler.description": "為量測提供直觀的介面。",
  "transform": "3D操作",
  "transform.description": "旋轉、移動和縮放您的設計以滿足您的需求。"
}
