=== woodcutapp/woodcutapp.github.io/public/lang/schema/home.json
{
  "$ref": "#/definitions/HomeJsonSchema",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "HomeJsonSchema": {
      "additionalProperties": false,
      "properties": {
        "app.name": {
          "type": "string"
        },
        "app.slogan": {
          "type": "string"
        },
        "app.text": {
          "type": "string"
        },
        "features": {
          "type": "string"
        },
        "help": {
          "type": "string"
        },
        "help.text": {
          "type": "string"
        },
        "start": {
          "type": "string"
        }
      },
      "required": [
        "app.name",
        "app.slogan",
        "app.text",
        "features",
        "help",
        "help.text",
        "start"
      ],
      "type": "object"
    }
  }
}

=== woodcutapp/woodcutapp.github.io/public/lang/en-US/home.json
{
  "$schema": "../schema/home.json",
  "app.name": "WoodCut",
  "app.slogan": "3D Design for Woodworking",
  "app.text": "WoodCut is a completely free 3D design tool for woodworking projects. Create detailed 3D models, generate optimized cutlists, and export to various formats.",
  "features": "What can you do with this app?",
  "help": "Need Help?",
  "help.text": "Please use the Github repository to report issues or request features, or join the Reddit community to ask questions or share your projects.",
  "start": "Start"
}
